services:
  db:
    container_name: expo_poc_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: root
      POSTGRES_DB: expoDB
    ports:
      - 5432:5432
    volumes:
      - expo_poc:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
     - db

volumes:
  expo_poc:
